package phpserialize

import (
	"reflect"
)

// Marshaler is the interface implemented by an object that can be serialized.
//
// PhpSerialize must return a value with one of the supported types:
// - bool
// - int/int8/int16/int32/int64
// - uint/uint8/uint16/uint32/uint64
// - float32/float64
// - string
// - []byte
// - struct
// - slice of supported types
// - map of supported types
// - pointer to a supported type
type Marshaler interface {
	PhpSerialize() (reflect.Value, error)
}

// Unmarshaler is the interface implemented by an object that can be
// deserialized from PHP serialized data.
//
// PhpUnserialize must be able to decode values generated by PhpSerialize. The
// data argument will be one the supported types as enumerated for Marshaler
// interface.
type Unmarshaler interface {
	PhpUnserialize(data interface{}) error
}
